from __future__ import annotations

import json
import os
import secrets
import shutil
import subprocess
import tempfile
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage

from seps.config import Settings
from seps.gh_cli import GhError, assert_gh_auth, gh_json, gh_run, git_subprocess_env
from seps.github_client import OrgClient
from seps.llm import get_chat_model


def _git(args: list[str], *, cwd: Path, settings: Settings) -> None:
    proc = subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        env=git_subprocess_env(settings),
    )
    if proc.returncode != 0:
        raise GhError(
            cmd=["git", *args],
            stdout=proc.stdout or "",
            stderr=proc.stderr or "",
            returncode=proc.returncode,
        )


def _open_handoff_pr_exists(
    settings: Settings, org: str, repo_short: str, issue_number: int
) -> bool:
    full = f"{org}/{repo_short}"
    rows = gh_json(
        ["pr", "list", "--repo", full, "--state", "open", "--json", "headRefName"],
        settings=settings,
    )
    if not rows:
        return False
    prefix = f"seps/handoff-{issue_number}-"
    return any(str(r.get("headRefName", "")).startswith(prefix) for r in rows)


def run_execute_issue(
    settings: Settings,
    repo_short: str,
    issue_number: int,
    *,
    dry_run: bool,
    with_llm: bool,
) -> str:
    """
    Clone target repo, add docs/seps-handoffs/issue-{n}.md from the GitHub issue, push a branch,
    and open a draft PR (Refs #n). Requires token with contents + pull-requests on the target repo.
    """
    assert_gh_auth(settings)
    org = settings.github_org
    full = f"{org}/{repo_short}"

    issue = gh_json(
        [
            "issue",
            "view",
            str(issue_number),
            "--repo",
            full,
            "--json",
            "title,body,labels",
        ],
        settings=settings,
    )
    if not issue:
        return f"Could not load issue #{issue_number} on {full}."

    raw_labels = issue.get("labels") or []
    labels: list[str] = []
    for lab in raw_labels:
        if isinstance(lab, str):
            labels.append(lab)
        else:
            labels.append(str(lab.get("name", "")))
    if "seps:task" not in labels:
        return f"Issue #{issue_number} is not labeled seps:task; refusing to open a handoff PR."

    if _open_handoff_pr_exists(settings, org, repo_short, issue_number):
        return (
            f"An open PR with branch prefix seps/handoff-{issue_number}- already exists; "
            "skipped duplicate handoff."
        )

    title = str(issue.get("title") or "")
    body = str(issue.get("body") or "")

    outline = ""
    if with_llm:
        llm = get_chat_model(settings)
        if llm:
            sys = SystemMessage(
                content=(
                    "You help implement a Solana/Anchor/GitHub SEPS repo. "
                    "Reply with a short markdown section only: bullet list of 5–12 concrete "
                    "implementation steps (files, instructions, tests). No preamble."
                )
            )
            human = HumanMessage(
                content=f"Issue title:\n{title}\n\nIssue body:\n{body}\n"
            )
            out = llm.invoke([sys, human])
            outline = out.content if isinstance(out.content, str) else str(out.content)
        else:
            outline = "_No LLM configured; skipped outline._\n"

    rel_path = f"docs/seps-handoffs/issue-{issue_number}.md"
    doc_lines = [
        f"# SEPS handoff — issue #{issue_number}",
        "",
        f"**Repository:** `{full}`",
        f"**Title:** {title}",
        "",
        "## Source issue body",
        "",
        body.strip() or "_empty_",
        "",
    ]
    if outline:
        doc_lines += ["## Suggested implementation outline", "", outline.strip(), ""]

    doc_lines += [
        "",
        "---",
        "_Draft PR generated by `seps execute`. Replace this file with real code changes, "
        "or close the PR if obsolete._",
        "",
    ]
    doc_text = "\n".join(doc_lines)

    if dry_run:
        return (
            f"[dry-run] would clone {full}, add {rel_path}, push branch "
            f"seps/handoff-{issue_number}-<id>, open draft PR (Refs #{issue_number})."
        )

    client = OrgClient(settings)
    base = client.default_branch(repo_short)

    root = Path(tempfile.mkdtemp(prefix="seps-exec-"))
    work = root / "repo"
    try:
        gh_run(
            ["repo", "clone", full, str(work), "--", "--depth", "1", "--branch", base],
            settings=settings,
            check=True,
        )

        suffix = secrets.token_hex(4)
        branch = f"seps/handoff-{issue_number}-{suffix}"

        handoff_path = work / rel_path
        handoff_path.parent.mkdir(parents=True, exist_ok=True)
        handoff_path.write_text(doc_text, encoding="utf-8")

        if os.environ.get("GITHUB_ACTIONS") == "true":
            actor, email = (
                "github-actions[bot]",
                "41898282+github-actions[bot]@users.noreply.github.com",
            )
        else:
            actor, email = "SEPS handoff", "seps-handoff@users.noreply.github.com"

        _git(["checkout", "-b", branch], cwd=work, settings=settings)
        _git(["add", rel_path], cwd=work, settings=settings)
        _git(
            [
                "-c",
                f"user.name={actor}",
                "-c",
                f"user.email={email}",
                "commit",
                "-m",
                f"seps: add handoff doc for issue #{issue_number}\n\nRefs #{issue_number}",
            ],
            cwd=work,
            settings=settings,
        )
        _git(["push", "-u", "origin", branch], cwd=work, settings=settings)

        pr_body = (
            f"Automated **draft** handoff for `seps:task` #{issue_number}.\n\n"
            f"- Adds `{rel_path}` from the issue at open time.\n"
            "- Replace with real implementation or close.\n\n"
            f"Refs #{issue_number}"
        )
        gh_run(
            [
                "pr",
                "create",
                "--repo",
                full,
                "--draft",
                "--base",
                base,
                "--head",
                branch,
                "--title",
                f"SEPS handoff: #{issue_number} — {title[:70]}",
                "--body",
                pr_body,
            ],
            settings=settings,
            check=True,
        )
        proc = gh_run(
            ["pr", "list", "--repo", full, "--head", branch, "--json", "url", "--limit", "1"],
            settings=settings,
            check=True,
        )
        pr_rows = json.loads(proc.stdout or "[]")
        url = pr_rows[0]["url"] if pr_rows else "(created)"
        return f"Opened draft PR: {url}"
    finally:
        shutil.rmtree(root, ignore_errors=True)
